
INSERT INTO shopping_list (name, price, category, checked)
VALUES
    ('Fish tricks', 13.10, 'Main',              false),
    ('Not Dogs', 4.99, 'Snack',                 true),
    ('Bluffalo Wings', 5.50, 'Snack',           false),
    ('SubstiTuna Salad', 1.24, 'Lunch',         false),
    ('Tofurkey', 2.50, 'Breakfast',             false),
    ('Pretenderloins', 9.99, 'Main',            false),
    ('Steak-believe', 6.00, 'Main',             false),
    ('Kale Seitan', 6.67, 'Breakfast',          false),
    ('NoBull Burger', 2.00, 'Snack',            false),
    ('Turnip the Beet', 0.20, 'Lunch',          true),
    ('Mascarphony', 1.80, 'Lunch',              true),
    ('Burgatory', 1.50, 'Main',                 false),
    ('Sleight of Ham', 3.10, 'Lunch',           false),
    ('Antichovies', 1.00, 'Breakfast',          false),
    ('Lettuce B. Frank', 0.86, 'Lunch',         true),
    ('Pepperphony', 1.40, 'Breakfast',          false),
    ('Shamburger', 3.50, 'Main',                false),
    ('Facon', 1.90, 'Breakfast',                false),
    ('Salami-get-this-straight', 3.00, 'Snack', false),
    ('Mi-steak', 7.67, 'Main',                  false),
    ('Ghost Beef', 4.33, 'Main',                false),
    ('Cheatloaf', 5.00, 'Main',                 false),
    ('Fried Trickin', 6.40, 'Snack',            false),
    ('Salmock', 7.16, 'Breakfast',              false),
    ('Leaf Stroganoff', 6.80, 'Main',           false),
    ('Chicken Noodle Spoof', 2.50, 'Lunch',     false),
    ('Pep-parody Pizza', 4.00, 'Lunch',         false),
    ('Arti-fish-al pie', 8.40, 'Main',          false),
    ('Bolphony sandwiches', 2.10, 'Lunch',      false),
    ('Chili non-carne', 5.88, 'Main',           true),
    ('Don''t go bacon my heart', 4.20, 'Main',  false)
;
